# Generated by Django 5.1.15 on 2026-10-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_units_categories'),
        ('inventory', '0001_initial'),
        ('locations', '0002_seed_locations'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='stock_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='requests.stockrequest'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stocktransfer'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='receipt_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'location'), name='one_balance_per_product_location'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='on_hand_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='reserved_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='reserved_within_on_hand'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'occurred_at'], name='inventory_s_product_060ca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='movement_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_location__isnull', False), ('to_location__isnull', False), _connector='OR'), name='movement_has_a_location'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('qty_delta', 0), _negated=True), name='adjustment_delta_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_sent__gt', 0)), name='transfer_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_received__isnull', True), ('qty_received__lte', models.F('qty_sent')), _connector='OR'), name='transfer_received_within_sent'),
        ),
    ]
