# Generated by Django 5.1.15 on 2026-10-06 13:56

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_wholesale_price'),
        ('inventory', '0003_transit_location'),
        ('locations', '0002_seed_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConditionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('qty', models.PositiveIntegerField()),
                ('from_condition', models.CharField(choices=[('new', 'New'), ('display', 'Display'), ('damaged', 'Damaged')], max_length=10)),
                ('to_condition', models.CharField(choices=[('new', 'New'), ('display', 'Display'), ('damaged', 'Damaged')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='stockbalance',
            name='reserved_within_on_hand',
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('display', 'Display'), ('damaged', 'Damaged')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='display',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('display', 'Display'), ('damaged', 'Damaged')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('display', 'Display'), ('damaged', 'Damaged')], default='new', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('display__gte', 0)), name='display_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('damaged__gte', 0)), name='damaged_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('on_hand'), '-', models.F('display')), '-', models.F('damaged')))), name='reserved_within_new_stock'),
        ),
        migrations.AddField(
            model_name='stockconditionchange',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location'),
        ),
        migrations.AddField(
            model_name='stockconditionchange',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockconditionchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='stockconditionchange',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='condition_change_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockconditionchange',
            constraint=models.CheckConstraint(condition=models.Q(('from_condition', models.F('to_condition')), _negated=True), name='condition_change_changes_something'),
        ),
    ]
