# Generated by Django 5.1.15 on 2026-10-05 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=40)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('bot', 'Bot'), ('system', 'System')], default='system', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['model', 'object_id'], name='audit_audit_model_6c2be1_idx')],
            },
        ),
    ]
