# Generated by Django 5.1.15 on 2026-10-06 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_units_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_type',
            field=models.CharField(choices=[('selling', 'Selling'), ('wholesale', 'Wholesale')], default='selling', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('wholesale_price__isnull', True), models.Q(('wholesale_price__gt', 0), ('wholesale_price__lte', models.F('selling_price'))), _connector='OR'), name='wholesale_price_positive_and_not_above_selling'),
        ),
    ]
