# Generated by Django 5.1.15 on 2026-10-05 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_units_categories'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('locations', '0002_seed_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('transaction_number', models.CharField(db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('partially_released', 'Partially Released'), ('released', 'Released'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to='customers.customer')),
                ('requesting_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('transaction_number', models.CharField(db_index=True, max_length=20)),
                ('destination_type', models.CharField(choices=[('branch', 'Branch'), ('customer_pickup', 'Customer Pickup')], max_length=20)),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release', to='inventory.stocktransfer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='requests.stockrequest')),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.PositiveIntegerField()),
                ('qty_released', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='requests.stockrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockReleaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='requests.stockrelease')),
                ('request_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_lines', to='requests.stockrequestline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockrequestline',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='one_line_per_product_per_request'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_requested__gt', 0)), name='request_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_released__lte', models.F('qty_requested'))), name='released_within_requested'),
        ),
        migrations.AddConstraint(
            model_name='stockreleaseline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='release_line_qty_positive'),
        ),
    ]
