# Generated by Django 5.1.15 on 2026-10-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_personal_payments', 'See Personal-account payments and totals'), ('verify_payments', 'Verify or reject recorded payments'), ('correct_payments', 'Reverse and re-record payments'), ('correct_transactions', 'Void or correct sales and stock movements'), ('approve_adjustments', 'Approve stock adjustments'), ('approve_credit', "Confirm sales beyond a customer's credit rules"), ('approve_discounts', 'Give discounts above the salesperson limit'), ('export_reports', 'Export reports to Excel')]},
        ),
    ]
