# Generated by Django 5.1.15 on 2026-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_personal_payments_for_all_staff'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_payment_accounts',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='payments.paymentaccount'),
        ),
    ]
