# Generated by Django 5.1.15 on 2026-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_wholesale_price'),
        ('locations', '0002_seed_locations'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorderline',
            name='one_line_per_product_per_order',
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('display', 'display'), ('damaged', 'damaged')], default='new', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'condition'), name='one_line_per_product_condition_per_order'),
        ),
    ]
